samba:
  image: dperson/samba
  container_name: samba
  ports:
    - "137:137/udp"
    - "138:138/udp"
    - "139:139/tcp"
    - "445:445/tcp"
  volumes:
    - ~/samba/pub:/mnt/pub:rw
  command:
    "-s public;/mnt/pub;yes;no;no;yuta,guest -u yuta;9895 -u guest;guest"
  restart: unless-stopped
